services:
  postgres:
    image: postgres:15.7
    container_name: backend-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # 실제 데이터가 저장되는 경로, 컨테이너 삭제해도 데이터 사라지지 않게 호스트 폴더와 동기화
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend_db"]
      interval: 5s # 5초 간격으로 확인하며, 5번 실패하면 문제가 있는 것으로 간주
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: test-elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: test-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
