plugins {
    id "java-library"
    id "org.springframework.boot"
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

ext {
    set('elasticsearchVersion', '8.18.0')
}

dependencies {
    api project(":common-data-access")
    api "co.elastic.clients:elasticsearch-java:${elasticsearchVersion}"
    api "org.springframework.boot:spring-boot-starter-json"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
}
