spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  api-docs:
    path: /users/v3/api-docs
  swagger-ui:
    path: /users/swagger-ui