plugins {
    id "java-library"
    id "org.springframework.boot"
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    api project(":common-data-access")
    api "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-security"
}
